extends: semistandard
env:
  browser: yes
  es6: yes
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-console:
    - warn
    - allow:
      - table
